<?php echo $this->doctype(); ?>

<html lang="en">
    <head>

    </head>
    <body>
        <header>
                <p>==============HEADER==============</p>
        </header>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
